import Head from "next/head";
import React, { useCallback, useState } from "react";
import { inter } from "@/common/fonts";
import { MapData, MapGameMode, mapData } from "@/services/map-service";
import { MapSelector } from "@/components/MapSelector";
import { GameModeSelector } from "@/components/GameModeSelector";
import styles from "@/styles/Home.module.css";
import { Map } from "@/components/Map";

const normalizeGameModeName = (gameModeName: string) =>
  gameModeName.replace(/ #\d$/, "");

export default function Home() {
  const [selectedMap, setSelectedMap] = useState<MapData | null>(mapData[0]);
  const [selectedGameMode, setSelectedGameMode] = useState<MapGameMode | null>(
    mapData[0].gameModes[0]
  );

  const handleMapChanged = useCallback((map: MapData | null) => {
    if (!map) {
      setSelectedMap(null);
      setSelectedGameMode(null);
      return;
    }

    setSelectedMap(map);
    setSelectedGameMode((currGameMode) => {
      if (!currGameMode) {
        return map.gameModes[0];
      }

      const gameModeWithSameName = map.gameModes.find(
        (gm) => gm.gameMode === currGameMode.gameMode
      );
      if (gameModeWithSameName) {
        return gameModeWithSameName;
      }

      const normalizedCurrentGameModeName = normalizeGameModeName(
        currGameMode.gameMode
      );

      const gameModeWithSameNormalizedName = map.gameModes.find(
        (gm) =>
          normalizeGameModeName(gm.gameMode) === normalizedCurrentGameModeName
      );

      return gameModeWithSameNormalizedName ?? map.gameModes[0];
    });
  }, []);

  return (
    <>
      <Head>
        <title>Ground Rangefinder for War Thunder</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={`${styles.container} ${inter.className}`}>
        <header className={styles.header}>
          <h1 className={styles.title}>
            Ground Map Distance Calculator
            <br />
            for War Thunder
          </h1>
          <p>
            {`Calculator for War Thunder's Ground Battles map grid distance.`}
          </p>
          <p>{`Click and hold on your tank's position and let go on where the enemy is on the map, and the tool automatically calculates the distance for you.`}</p>
        </header>

        <main className={styles.main}>
          <div className={styles.searchBar}>
            <div className={styles.searchBarCell}>
              <label htmlFor="map-selector">Map</label>
              <MapSelector
                id="map-selector"
                maps={mapData}
                onChange={handleMapChanged}
                value={selectedMap}
              />
            </div>
            <div className={styles.searchBarCell}>
              <label htmlFor="game-mode-selector">Game Mode</label>
              <GameModeSelector
                id="game-mode-selector"
                gameModes={selectedMap?.gameModes ?? []}
                onChange={setSelectedGameMode}
                value={selectedGameMode}
              />
            </div>
          </div>

          {selectedMap && selectedGameMode ? (
            <Map mapName={selectedMap.name} gameMode={selectedGameMode} />
          ) : null}
        </main>
      </div>
    </>
  );
}
